Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 2:
> > 
> > > Patch Set 1:
> > > 
> > > I think you missed a carriage return - the title is a bit long.. 😊
> > > would it be possible to plan a demo of these tests during an integration weekly meeting?
> > > not this week as it is public holiday in Poland but maybe next week
> > > 
> > > WOuld some ofg the TC be suitable for End to End tests in CI/CD chains (in addition of functional/CSIT tests)
> > 
> > Hi Morgan, 
> > I've updated commit message. Hope this will be suitable. 
> > It would be pleasure to prepare a demo of these tests during integration weekly meeting.
> > Next week will be fine.
> > For now I'm not sure if the prepared TC will be suitable for End to End tests. There are
> > 6 TC prepared to cover CSIT tests with HTTP. Corresponding auto-tests are in the autotests
> > directory, but for now I'm not sure how or if they are used in CI/CD chains.
> 
> Ok I planned a 15 minutes slot on the 13th : https://wiki.onap.org/display/Meetings/%5Bintegration%5D+ONAP+2%2C+Wed+UTC+13%3A00

Thank you for your info.
Additionally, I have some more questions:
- I have one failed test - https://jenkins.onap.org/job/integration-master-md-lint/33/ 
  It is related to "md" files validation, but ERROR message seem to be not so informative for me:
ERROR: InvocationError for command /bin/bash -c 'coala --non-interactive --disable-caching --no-autoapply-warn md --files $(</tmp/.coalist_md) \ ' (exited with code 5)

coala help says:
5 - coala executed successfully. Results were found but patches to the results were applied successfully (http://docs.coala.io/en/latest/Users/Exit_Codes.html)

So I will expect successfully ended test or failed but with some patch file to make corrections
manually.
Additionally I saw, that just before Christmas some jenkins configuration related to this was changed (https://jenkins.onap.org/job/integration-master-md-lint/jobConfigHistory/showDiffFiles?timestamp1=2020-12-16_13-02-35&timestamp2=2021-01-04_19-03-49)

Are these two cases related? Do you have any suggestions how to solve this?

- Regarding this patchset, it could be merged before or after demo?
- Note, after merging this patchset I will do next push with csit tests to csit repo.

Patch-set: 2