Update patch set 1
Patch Set 1: Verified+1

Application fail to run as werkzeug was missing cryptography library:

  File "(...)lib/python3.6/site-packages/werkzeug/serving.py", line 512, in generate_adhoc_ssl_pair
    raise TypeError("Using ad-hoc certificates requires the cryptography library.")
TypeError: Using ad-hoc certificates requires the cryptography library.

Patch-set: 1
Reviewer: Gerrit User 5097 <5097@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Label: Verified=+1